### ISSUE TITLE
*** ValueError: Unknown format 1, attempted to normalize to '0x1'

### ISSUE THREAD

**Issue by PatrickAlphaC** [vyperlang/titanoboa#322]
Try the following:

1. Setup an anvil chain in a separate terminal

```
anvil
````

2. Setup your db, and deploy a contract, then try to read from it
```python
from boa.deployments import DeploymentsDB, set_deployments_db
from boa.network import EthereumRPC
import boa
from boa import NetworkEnv
from eth_account import Account

# Setup DB
db = DeploymentsDB(path="my_db.db")
set_deployments_db(db)

# Setup ENV
env = NetworkEnv(EthereumRPC("http://127.0.0.1:8545"), nickname="anvil")
boa.set_env(env)

# Setup Account
## Don't worry, this is an anvil default key, very public
account = Account.from_key("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80")
boa.env.set_eoa(account)

# Setup Contract
my_code ="""# pragma version 0.4.0
number: public(uint256)"""
deployer = boa.loads_partial(my_code)
contract = deployer.deploy()

# Test it out, this works fine:
db.get_deployments()

# This does not:
sql_resp = db._get_deployments_from_sql("SELECT * FROM deployments")
```

You'll get this error:
```
*** ValueError: Unknown format 1, attempted to normalize to '0x1'
```

Full trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/moccasin/.venv/lib/python3.12/site-packages/boa/deployments.py", line 129, in _get_deployments_from_sql
    ret = [Deployment.from_sql_tuple(item) for item in cur.fetchall()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/moccasin/.venv/lib/python3.12/site-packages/boa/deployments.py", line 72, in from_sql_tuple
    ret["contract_address"] = Address(ret["contract_address"])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/moccasin/.venv/lib/python3.12/site-packages/boa/util/abi.py", line 37, in __new__
    checksum_address = to_checksum_address(address)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/moccasin/.venv/lib/python3.12/site-packages/eth_utils/address.py", line 127, in to_checksum_address
    norm_address = to_normalized_address(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/moccasin/.venv/lib/python3.12/site-packages/eth_utils/address.py", line 79, in to_normalized_address
    raise ValueError(
ValueError: Unknown format 1, attempted to normalize to '0x1'
```

**Comment by PatrickAlphaC** [comment]
It looks like you can't do `select *` instead, you have to do:

```python
fields = db._get_fieldnames_str()
sql = f"select {fields} from deployments"
```
