### ISSUE TITLE
Bug: AttributeError: 'VyperDeployer' object has no attribute 'wrap'

### ISSUE THREAD

**Issue by PatrickAlphaC** [vyperlang/titanoboa#73]
I have a factory contract that has a function `create_simple_storage_contract` which returns the address of a contract it just deployed:

```python
import boa

simple_storage = boa.load("SimpleStorage.vy")
storage_factory = boa.load("StorageFactory.vy", simple_storage.address)
new_simple_storage_address = storage_factory.create_simple_storage_contract()

# Breaks
new_simple_storage_contract_deployer = simple_storage.at(new_simple_storage_address)
```

However, when I try to get a `VyperContract` object using `at` I get an error:

```
Traceback (most recent call last):
  File "/xxx/deploy_from_storage_factory.py", line 10, in <module>
    new_simple_storage_contract_deployer = simple_storage.at(new_simple_storage_address)
  File "/xxx/site-packages/boa/contract.py", line 418, in at
    return self.deployer.wrap(*args, **kwargs)
AttributeError: 'VyperDeployer' object has no attribute 'wrap'
```

**Comment by PatrickAlphaC** [comment]
Just tried this from master:

```
Traceback (most recent call last):
  File "xxxdeploy_from_storage_factory.py", line 17, in <module>
    import boa
  File "/xxx/site-packages/boa/__init__.py", line 4, in <module>
    from boa.contract import check_boa_error_matches
  File "/xxx/site-packages/boa/contract.py", line 19, in <module>
    import vyper.semantics.validation as validation
    ```

**Comment by PatrickAlphaC** [comment]
Tried by forcing an upgrade in a fresh environment. 

```
vyper==0.3.7
titanoboa==0.1.6
```

```
Traceback (most recent call last):
  File "/Users/patrick/code/vyper-full-course/boa-simple-storage-factory-v23/deploy_from_storage_factory.py", line 17, in <module>
    import boa
  File "/Users/patrick/code/vyper-full-course/boa-simple-storage-factory-v23/venv/lib/python3.10/site-packages/boa/__init__.py", line 4, in <module>
    from boa.contract import check_boa_error_matches
  File "/Users/patrick/code/vyper-full-course/boa-simple-storage-factory-v23/venv/lib/python3.10/site-packages/boa/contract.py", line 35, in <module>
    from boa.environment import AddressT, Env, to_int
  File "/Users/patrick/code/vyper-full-course/boa-simple-storage-factory-v23/venv/lib/python3.10/site-packages/boa/environment.py", line 18, in <module>
    from eth_abi import decode_single
ImportError: cannot import name 'decode_single' from 'eth_abi' (/Users/patrick/code/vyper-full-course/boa-simple-storage-factory-v23/venv/lib/python3.10/site-packages/eth_abi/__init__.py)
```

**Comment by PatrickAlphaC** [comment]
an force upgrade fixed it. thanks!
